In [30]:
from activation import relu, sigmoid, softmax
from loss import mse, cross_entropy_err
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.datasets import fetch_openml

In [3]:
mnist = fetch_openml('mnist_784')

In [4]:
x = mnist.data
y = mnist.target

In [5]:
with open('sample_weight.pkl', 'rb') as f:
    network = pickle.load(f)

In [6]:
# plt.imshow(x.loc[[0],:].values.reshape(28,28))

# weight['W1'].shape, weight['W2'].shape, weight['W3'].shape
# # 분류할 개수가 0~9 10개이므로 출력은 10

# x.loc[0,:].values.reshape(1,784).shape # (데이터 개수, 크기)

# # 첫번째 레이어를 통과하는 값, 예시로 첫번쨰값 하나만
# l1 = np.dot(x.loc[0,:].values.reshape(1,784), weight['W1']) + weight['b1']
# a1 = sigmoid(l1) # 활성화 함수

# l2 = np.dot(a1, weight['W2']) + weight['b2']
# a2 = sigmoid(l2)

# l3 = np.dot(a2, weight['W3']) + weight['b3']

# np.argmax(l3)

In [7]:
weight['W1'].shape, weight['W2'].shape, weight['W3'].shape

NameError: name 'weight' is not defined

In [8]:
def predict(x):
    W1, W2, W3 = weight['W1'], weight['W2'], weight['W3']
    b1, b2, b3 = weight['b1'], weight['b2'], weight['b3']
    
    h1 = np.dot(x, W1) + b1
    a1 = sigmoid(h1)
    h2 = np.dot(a1, W2) + b2
    a2 = sigmoid(h2)
    out = np.dot(a2, W3) + b3
    out = np.argmax(out, axis=1).astype('str')
    # result = softmax(out)  
    return out

def accuracy(x,y):
    return sum(predict(x) == y.values) /y.size

In [6]:
def predict(x, network):
    input_layer = x
    layers = []
    bias = []
    num_layer = int(len(network.keys())/2)
    for i in range(num_layer):
        layers.append(network['W'+str(i+1)])
        bias.append(network['b'+str(i+1)])
    for i in range(num_layer):
        if num_layer != i:
            input_layer = sigmoid(np.dot(input_layer,layers[i]) + bias[i])
        else:
            input_layer = np.dot(input_layer,layers[i]) + bias[i]
    # return np.argmax(input_layer, axis=1).astype('str')
    return softmax(input_layer)

In [10]:
x.shape

(70000, 784)

In [11]:
accuracy(x,y)

TypeError: predict() missing 1 required positional argument: 'network'

In [12]:
pre = predict(x.values, network)

/home/ejchoi/work_place/activation.py:4: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [13]:
sum(pre == y)/y.size

0.0

In [14]:
relu(np.dot(x,network['W1']))

array([[ 991.38860958,    0.        ,    0.        , ...,  461.81789378,
           0.        ,    0.        ],
       [1251.53191894,  865.42200546,    0.        , ...,  297.65761123,
           0.        ,   43.0190886 ],
       [   0.        ,  384.96450885,  522.83004731, ...,    0.        ,
         359.95052797,  276.16372561],
       ...,
       [   0.        ,    0.        ,  620.68962102, ...,    0.        ,
         507.20683358,  220.44589879],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
         350.09469865,   55.06031603],
       [ 757.27764039, 1793.27601436,    0.        , ...,    0.        ,
         587.88680071,  933.27330242]])

In [15]:
# y 값을 one_hot -- tk
# network를 softmax로 풀기 -- 값이 총 10개 나옴
# -sum(tk * log(yk))

In [16]:
y_ohe = pd.get_dummies(y)

In [17]:
tk = np.array(y_ohe)

In [18]:
yk = predict(x, network).astype('int')

In [19]:
E = -sum(tk*np.log(yk))

/tmp/ipykernel_4199/2153940171.py:1: RuntimeWarning: divide by zero encountered in log
  E = -sum(tk*np.log(yk))
/tmp/ipykernel_4199/2153940171.py:1: RuntimeWarning: invalid value encountered in multiply
  E = -sum(tk*np.log(yk))


In [20]:
tk.shape, yk.shape

((70000, 10), (70000, 10))

In [21]:
def f(x):
    return x**2

In [22]:
def der_f(x):
    return 2*x

In [23]:
der_f(3)

6

In [24]:
y[predict(x,network) != y]

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [25]:
y[24]

'1'

In [26]:
tt = np.array([0,0,0,0,0,1,0,0,0,0])
tf = np.array([0,1,0,0,0,0,0,0,0,0])

In [27]:
yt = softmax(predict(x,network)[0])
yf = softmax(predict(x,network)[24])

In [28]:
# 교차 엔트로피 오차 Cross Entropy Error(CEE)
-np.sum(yf*np.log(tf+1e-7))

14.506284997194204

In [29]:
1/2*np.sum((yt-tt)**2)

0.449999917958371

In [30]:
1/2*np.sum((yf-tf)**2)

0.4499999330772068

In [31]:
p = softmax(f)

TypeError: unsupported operand type(s) for -: 'function' and 'function'

In [7]:
def mse(y,t):
    return (1/2*np.sum((y-t)**2))/y.size

In [8]:
def cross_entropy_err(y,t):
    return np.sum(-np.sum(t*np.log(y)))/y.size

In [9]:
y_ohe = np.array(pd.get_dummies(pd.DataFrame(y)))
y_ohe

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [10]:
y = y.values.astype(np.int)

/tmp/ipykernel_4235/1431651893.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = y.values.astype(np.int)


In [11]:
y_one = np.zeros((y.size,np.unique(y).size))

In [12]:
for i in range(y.size):
    y_one[i,y[i]] = 1

In [13]:
y_one

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
mse(predict(x,network),y_one)

/home/ejchoi/work_place/activation.py:4: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


NameError: name 'a' is not defined

In [15]:
cross_entropy_err(predict(x,network),y_one)

NameError: name 'a' is not defined

In [31]:
dt = np.random.randint(1,100,40000)
X = dt.reshape(10000,4)
t = np.zeros((10000,3))
for i in range(10000):
    t[i,np.random.randint(0,3,1)]=1

In [32]:
W1 = np.random.randn(4,100)
W2 = np.random.randn(100,70)
W3 = np.random.randn(70,50)
W4 = np.random.randn(50,3)
weights = {
    'W1':W1,
    'W2':W2,
    'W3':W3,
    'W4':W4,
}

def network():
    return weights

In [33]:
init_network = network()

In [36]:
def softmax(x):
    c = np.max(x)
    a = x - c
    return np.exp(a)/np.sum(np.exp(a))

In [41]:
input_data = X
layer1 = np.dot(input_data, init_network['W1'])
relu1 = relu(layer1)
layer2 = np.dot(relu1, init_network['W2'])
sigmoid1 = sigmoid(layer2)
layer3 = np.dot(sigmoid1, init_network['W3'])
relu2 = relu(layer3)
output = np.dot(relu2, init_network['W4'])
y = softmax(output)
# y = np.apply_along_axis(softmax,1,output)

/home/ejchoi/work_place/activation.py:4: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [42]:
cross_entropy_err(y,t)

5.343500048225049