In [23]:
import numpy as np

In [36]:
class MulGraph:
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self,x,y):
        self.x = x
        self.y = y
        out = x*y
        return out
    
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        return dx, dy


In [53]:
class AddGraph:
    def __init__(self):
        pass
    
    def forward(self,x,y):
        out = x + y
        return out
    
    def backward(self,dout):
        dx = dout*1
        dy = dout*1
        return dx, dy

In [55]:
x1 = 5
x2 = 3
x3 = 4

f1 = AddGraph()
f2 = AddGraph()
part_sum = f1.forward(x1,x2)
total_sum = f2.forward(part_sum,x3)
total_sum

12

In [57]:
dout = 1
df1, dx3 = f2.backward(dout)
df1, dx3

(1, 1)

In [38]:
apple = 100
number = 2
tax = 1.1

cal_apple = MulGraph()
cal_tax = MulGraph()

In [39]:
apple_price = cal_apple.forward(apple,number)
total_price = cal_tax.forward(apple_price,tax)
apple_price, total_price

(200, 220.00000000000003)

In [40]:
dout = 1
dapple_price, tax = cal_tax.backward(dout)
dapple_price, tax

(1.1, 200)

In [41]:
dout = dapple_price
dapple, dnumber = cal_apple.backward(dout)
dapple, dnumber

(2.2, 110.00000000000001)

In [42]:
dout = 1
dnumber, dapple = cal_tax.backward(dout)
dapple_price, dtax = cal_tax.backward(dout)

In [43]:
dtax

200

In [4]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
    
    def forward(self,x,y):
        self.x = x
        self.y = y        
        out = self.x*self.y
        return out
    
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        return dx, dy
    
class AddLayer:
    def __init__(self):
        pass
    
    def forward(self,x,y):
        out = x + y
        return out
    
    def backward(self,dout):
        dx = dout*1
        dy = dout*1
        return dx, dy

In [5]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1
# total_price
# dApple
# dApple_num
# dOrange
# dOrange_num
# dTax

In [7]:
apple_m = MulLayer()
orange_m = MulLayer()

apple_price = apple_m.forward(apple,apple_num)
orange_price = orange_m.forward(orange,orange_num)

total_a = AddLayer()
price = total_a.forward(apple_price,orange_price)

tax_m = MulLayer()
total_price = tax_m.forward(price,tax)

In [8]:
apple_price, orange_price, price, total_price

(200, 450, 650, 715.0000000000001)

In [14]:
dout = 1
dPrice, dTax = tax_m.backward(dout)
dPrice, dTax

(1.1, 650)

In [16]:
dapple, dorange = total_a.backward(dPrice)
dapple, dorange

(1.1, 1.1)

In [18]:
dApple, dApple_num = apple_m.backward(dapple)
dOrange, dOrange_num = orange_m.backward(dorange)

dApple, dApple_num, dOrange, dOrange_num

(2.2, 110.00000000000001, 3.3000000000000003, 165.0)

In [20]:
x = [1,2,3,4]

In [21]:
x[:3]

[1, 2, 3]

In [29]:
# 펜시 인덱싱 numpy로만 가능

In [25]:
x[[0,2]]

TypeError: list indices must be integers or slices, not list

In [26]:
np.array(x)[[0,2]]

array([1, 3])

In [27]:
x[[True,True,False,False]]

TypeError: list indices must be integers or slices, not list

In [28]:
np.array(x)[[True,True,False,False]]

array([1, 2])

In [19]:
def relu(x):
    return np.where(x > 0, x, 0)

In [30]:
class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <= 0)
        out = x.copy() # x가 계속 갱신될 필요가 있으므로 copy() 사용
        out[self.mask] = 0
        return out
    
    def backward(self,dout):
        dout[self.mask] = 0
        dx = dout
        return dx

In [31]:
relu_layer = Relu()

In [32]:
x = np.random.randn(4,2)

In [35]:
xf = relu_layer.forward(x)
xf

array([[0.        , 1.25040006],
       [0.        , 1.18654984],
       [0.        , 0.01874814],
       [0.22650207, 0.        ]])

In [40]:
xb = relu_layer.backward(xf)
xb

array([[0.        , 1.25040006],
       [0.        , 1.18654984],
       [0.        , 0.01874814],
       [0.22650207, 0.        ]])

In [38]:
x_mask = (x <= 0)
x_mask

array([[ True, False],
       [ True, False],
       [ True, False],
       [False,  True]])

In [56]:
class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self,x):
        out = 1 / (1+np.exp(-x))
        self.out = out
        return out
    
    def backward(self,dout):
        dx = dout*self.out*(1-self.out)
        return dx

In [57]:
x = np.random.randn(4,2)

In [58]:
sigmoidL = Sigmoid()
sf = sigmoidL.forward(x)
sb = sigmoidL.backward(sf)

In [62]:
x, sf, sb

(array([[-1.53100607,  0.08473347],
        [ 1.33005494, -0.66322069],
        [-1.86256424,  1.5768166 ],
        [-0.13970438, -1.74072231]]),
 array([[0.17784653, 0.5211707 ],
        [0.79084972, 0.3400165 ],
        [0.13440445, 0.8287532 ],
        [0.4651306 , 0.14922121]]),
 array([[0.02600421, 0.13005909],
        [0.13081164, 0.0763015 ],
        [0.0156366 , 0.11761776],
        [0.11571711, 0.01894427]]))

In [90]:
# Affine 미분

In [75]:
X = np.random.randn(2)
W = np.random.randn(2,3)
b = np.random.randn(3)

In [76]:
X.shape, W.shape, b.shape

((2,), (2, 3), (3,))

In [77]:
out = np.dot(X,W) + b

In [78]:
out.shape

(3,)

In [83]:
x = np.array([[0,0,0],[10.,10,10]])
b = np.array([1,2,3])
out = x + b

In [84]:
dy = np.arange(1,7).reshape(2,3)

In [88]:
dB = np.sum(dy, axis=0)

In [89]:
dB

array([5, 7, 9])

In [98]:
class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self,x):
        self.x = x
        out = np.dot(x,self.W) + self.b
        return out
    
    def backward(self,dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T,dout)
        self.db = np.sum(dout,axis=0)
        return dx

In [100]:
x = np.random.randn(4,2)
W = np.random.randn(2,3)
b = np.random.randn(3)

In [103]:
affine = Affine(W,b)

In [104]:
out = affine.forward(x)

In [106]:
sig = Sigmoid()
sig_out = sig.forward(out)

In [108]:
out,sig_out

(array([[-0.58262584, -1.21890072,  0.0133403 ],
        [ 0.00563857, -2.08854434,  0.9149887 ],
        [ 0.81942957, -0.47276445, -0.87412644],
        [ 0.11408169, -0.60496697, -0.68959524]]),
 array([[0.35832861, 0.22812996, 0.50333503],
        [0.50140964, 0.11021525, 0.71401992],
        [0.69411524, 0.38396214, 0.2943964 ],
        [0.52848953, 0.35320815, 0.33412312]]))

In [109]:
out.shape, sig_out.shape

((4, 3), (4, 3))

In [110]:
affine.backward(out)

array([[ 0.51474398, -1.05766328],
       [ 1.90522915, -0.93327798],
       [ 0.09199917,  1.18965884],
       [-0.01767881,  0.22736365]])

In [112]:
affine.db

array([ 0.35652398, -4.38517648, -0.63539267])

In [126]:
from activation import *
from loss import *
from gradient import *

In [124]:
x = np.random.randn(5,3)
w1 = np.random.randn(3,4)
b1 = np.random.randn(4)
w2 = np.random.randn(4,3)
b2 = np.random.randn(3)
t = np.zeros((5,3))
t[:,1] = 1

In [128]:
l1 = np.dot(x,w1) + b1
z1 = relu(l1)
l2 = np.dot(z1,w2) + b2
cross_entropy_error(softmax(l2),t)

4.501796757197233

In [139]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
    
    def forward(self,x,t):
        self.y = softmax(x)
        self.t = t
        self.loss = cross_entropy_error(self.y,self.t)
        return self.loss
    
    def backward(self,dout=1):
        dx = dout*(self.y - self.t) / self.y.shape[0]
        return dx

In [140]:
dL = SoftmaxWithLoss()

In [141]:
dLfoward = dL.forward(l2,t)

In [142]:
dL.backward()

array([[ 0.15370173, -0.19931378,  0.04561204],
       [ 0.16960066, -0.19967781,  0.03007715],
       [ 0.01247399, -0.19224987,  0.17977588],
       [ 0.01202121, -0.19401626,  0.18199505],
       [ 0.01178379, -0.19476743,  0.18298364]])

In [143]:
dL.backward().shape, l2.shape

((5, 3), (5, 3))